version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - POSTGRES_DB=payout_db
      - POSTGRES_USER=payout_user
      - POSTGRES_PASSWORD=payout_pass
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payout_db
      POSTGRES_USER: payout_user
      POSTGRES_PASSWORD: payout_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payout_user"]
      interval: 5s
  redis:
    image: redis:7-alpine
  celery_worker:
    build: .
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=payout_db
      - POSTGRES_USER=payout_user
      - POSTGRES_PASSWORD=payout_pass
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: bash -c "cd src && celery -A config worker -l INFO"
volumes:
  postgres_data:
